name: Basic Checks

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: "Unit Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        run: gradle ktlintCheck

      - name: Unit Tests
        run: gradle test
